#!/usr/bin/env bash
#script for 9th task
echo "$$" > /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I hate the kill command" 15
    trap "rm /var/run/myscript.pid" 2 15
done




