#!/usr/bin/env bash
#script for 9th task
echo "$$" > /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I hate the kill command; exit" SIGTERM
    trap "echo Y U no love me?!; exit" SIGINT
    trap "rm /var/run/myscript.pid; exit" EXIT SIGQUIT SIGTERM
done



