#!/usr/bin/env bash
#script for 9th task
echo "$$" > /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap "I hate the kill command" 15
    trap "Y U no love me?!" 2	
done




