#!/usr/bin/env bash
#final boss, oh yeah
case “$1” in
   start)
            ./manage_my_process start
            echo "$$" > /var/run/my_process.pid
            echo "manage_my_process started"
            ;;
   stop) 
            ./manage_my_process stop
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
            ;;
   restart)
            ./manage_my_process stop
            rm /var/run/my_process.pid
	    ./manage_my_process start
	    echo "$$" > /var/run/my_process.pid
            echo "manage_my_process restarted"
            ;;
   *)
            echo “Usage: manage_my_process {start|stop|restart}”
            exit 1
            ;;
esac
